---
title: "Review Reports"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["./uni-ulm.css", "./uni-ulm-fonts.css"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      beforeInit: "https://platform.twitter.com/widgets.js"
    includes:
      in_header: ./header.html 
#xaringan::inf_mr() #[Start Preview -> Type into console]
---

.instructions[In ihrem Peer Review sollten Sie die Arbeit ihrer Kommilitonen bewerten und kritisch hinterfragen.]

- Jeder Projektkursteilnehmer bekommt zufällig die Ausarbeitung des Projekts einer anderen Gruppe zugewiesen.
- Ergebnisse, vor allem Beschreibungen und Interpretationen, kritisch hinterfragen und Verbesserungen an der Ausarbeitung anregen.

**Ziele des Review Reports:**
- Die Gruppe mit deren Arbeit Sie sich auseinandersetzen sollte durch ihre Feedback _Hinweise erhalten_, wo die **Stärken** und vor allem auch **Schwächen** ihrer Arbeit lagen und wie Sie diese beim nächsten Projekt vermeiden kann
- Sie selbst können neue Ideen sammeln, wie bestimmte Sachverhalte dargestellt werden können 

--

.alert[**Helfen** Sie sich gegenseitig! Verfassen Sie ihre Reports _nicht nett_, sondern _kritisch und konstruktiv_!]

---

## Anonymität

Sie führen den Peer-Review im sogenannten Double-Blind-Verfahren durch. D.h. weder Sie wissen welche Gruppe die Projektarbeit verfasst hat, noch weiß die Gruppe später, wer den Review Report verfasst hat.

- Bitte geben Sie _konstruktives_ Feedback und sparen Sie nicht mit Kritik! Nur durch Kritik und den Hinweis auf Fehler können sich die Gruppen verbessern
- Bitte werden Sie in ihrem **Feedback nicht beleidigend**! Grundsätzlich gilt: Schreiben Sie nichts, was Sie nicht auch der Gruppe persönlich sagen würden.

---

## Aufbau des Peer Review Reports

- Starten Sie mit einer _kurzen Zusammenfassung_ der Arbeit die Sie reviewen sollen, gehen Sie hierbei auf die Idee des Projekts, die Hauptargumente und die gefunden Ergebnisse ein.
- Anschließend sollten Sie auf die positiven Aspekte der vorliegenden Projektarbeit eingehen. Stellen Sie gute Grafiken, Interpretationen etc. heraus. 
- Im Anschluss sollten Sie ihre Kritik an der vorliegenden Arbeit formulieren. Greifen Sie die Hauptpunkte der Autoren auf und überlegen Sie, ob diese Argumente in dem Projekt ihrer Meinung nach so angebracht werden können. 
    - Gestalten Sie ihre Kritik _konstruktiv_ indem Sie alternative Darstellungen und/oder Interpretationen vorschlagen

---

## Fragen die Sie im Review Report aufgreifen und beantworten sollten

**Fragen für die Zusammenfassung:**
- Was ist die Hauptaussage der Projektarbeit? Was lernen Sie aus der vorliegenden Projektarbeit? 

**Fragen für die positiven Aspekte:**
- Was sind die größten Pluspunkte der Projektarbeit, was war besonders gut?
- Welcher Abschnitt war für Sie besonders interessant und warum?

---

**Fragen für die Kritik:**

- Sind die Schaubilder schön gestaltet (Legende, Überschrift, Visualisierung insgesamt, ...) und die Tabellen gut dargestellt (Nachkommastellen, Beschriftung ...)
- Ist die Interpretation der Schaubilder nachvollziehbar? Was fehlt ihnen?
- Sind die Interpretationen der Schaubilder und Ergebnisse nachvollziehbar? Nennen Sie zwei Stellen an denen diese konkret verbessert werden können!
- Welcher Abschnitt war für Sie verwirrend an der Projektarbeit und wie könnte dieser Abschnitt klarer formuliert werden/die Grafik besser gemacht werden?
- Welche drei Punkte sollten die Autoren noch verbessern um ihren Projektarbeit aufzuwerten?

**Fragen für Sie:**

- Wenn Sie nach ihrem Feedback zu ihrer eigenen Projektarbeit zurückkehren dürften, was würden Sie ändern?

---

## Umfang des Review Reports

- Der Review Report sollte 1/2 bis maximal 1 Seite umfassen
- Er sollte im Fließtext verfasst sein, wobei Sie sich an der Beantwortung der vorherigen Fragen orientieren können
- Er sollte _konstruktiv_ und _mit konkreten Verbesserungsvorschlägen_ verfasst werden
- Er sollte als github-Dokument verfasst werden (Änderung im YAML-Header, Beispieldatei wurde in ihr Repositorium gepushed)

---

## Bewertung des Review Reports

```{r, eval=FALSE, warning=FALSE, message=FALSE}
---
title: "Feedback Formular für Gruppen"
output: github_document
params:
  hilfreich: 4
  spezifisch: 4
  reflektiert: 3
  ranking: 2
---
```

---

## Bewertung des Review Reports

- _Jede Gruppe_ erhält zwischen 3-4 Review Reports
- Die Bewertung der Reports erfolgt von _jeder Gruppe_ auf der Basis folgender Kriterien:

a) Wie hilfreich war der Report?
  - Bewertung auf einer Skala von 0 bis 5 (0 = nicht hilfreich)
  - Hinweise um dies bewerten zu können:
    - Gabe es hilfreiche Kritik?
    - Ist die Kritik nachvollziehbar?
    - Können Sie als Gruppe diese Kritik dazu nutzen ihre nächste Projektarbeit aufzuwerten?

---

## Bewertung des Review Reports

b) Wie spezifisch war der Report?
  - Bewertung auf einer Skala von 0 bis 5 (0 = sehr unspezifisch)
  - Hinweise um dies bewerten zu können:
    - Hatten Sie das Gefühl ihre Arbeit wurde gelesen und verstanden?
    - Wurden Kommentare angebracht, welche auf Probleme in ihren Antworten/Grafiken eingehen?
    - Wurden Probleme in ihrer Interpretation aufgedeckt und auf diese verwiesen?
 

c) Wie reflektiert war der Report?
  - Bewertung auf einer Skala von 0 bis 5 (0 = unreflektiert)
  - Hinweise um dies bewerten zu können:
    - Hat der Autor des Reports etwas aus ihrer Ausarbeitung gelernt?

---

## Bewertung des Review Reports

d) Wie ist ihr Gesamturteil zum erhalten Report im Verhältnis zu den anderen Reports (Ranking)?
  - Bewertung auf einer Skala von 1 bis 4 (1 = bester Report)
  - Hinweise um dies bewerten zu können:
    - Gegeben aller Review Reports die ihnen vorliegen: Welcher hat Ihnen am Meisten gebracht, welcher am wenigsten?










